### ISSUE TITLE
Any compatibility/version for micropython? (Pico W)

### ISSUE THREAD

**Issue by sgbaird** [ArduCAM/PICO_SPI_CAM#8]
Pico W has limited support for WiFi via CircuitPython. Can I use this to read images to an array via MicroPython?

**Comment by sgbaird** [comment]
I verified that this doesn't work (out-of-the-box at least) with the Pico W. Following the instructions at https://www.arducam.com/docs/pico/arducam-camera-module-for-raspberry-pi-pico/spi-camera-for-raspberry-pi-pico/

I get the following while running [`ArduCAM_Mini_2MP_Plus_VideoStreaming.py`](https://github.com/ArduCAM/PICO_SPI_CAM/blob/master/Python/ArduCAM_Mini_2MP_Plus_VideoStreaming.py):

```python
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
  File "/lib/Arducam.py", line 176, in __init__
TimeoutError: Clock stretch too long
```

Maybe related? https://github.com/adafruit/circuitpython/issues/4221 https://github.com/adafruit/circuitpython/issues/4082 https://github.com/micropython/micropython/issues/8167
